title: stillwater
email: victorylee201304@gmail.com
description: "Hello, My Name is stillwater, I'm a software Engineer and Web Developer from China. "
small_description: "A software Engineer and Web Developer from China. "
baseurl: ""
url: "stillwater.me"
twitter_username:
github_username:  superstar4
google_username:  https://plus.google.com/u/0/101869488504092117335/posts
weibo_username:  http://weibo.com/u/3948730723
# Build settings
#markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

markdown: RDiscount

compress_html:
clippings: [div, p, ul, td, h1, h2]
endings: []
ignore:
envs: []

comments :
    provider : duoshuo
    duoshuo : 
      short_name : stillwater

owner :
    name : stillwater
    interest : Program